CREATE TABLE AIRCRAFT("ID" INT not null primary key, "CALLSIGN" VARCHAR(7), "SQUAWK" VARCHAR(4), "REG" VARCHAR(6),
"FLIGHTNO" VARCHAR(10), "ROUTE" VARCHAR(25), "TYPE" VARCHAR(4), "CATEGORY" VARCHAR(2),
"ALTITUDE" SMALLINT, "HEADING" SMALLINT, "SPEED" SMALLINT, "VERTRATE" SMALLINT, "SELECTEDALTITUDE" SMALLINT,
"LAT" DOUBLE, "LON" DOUBLE, "BAROMETER" DOUBLE, "POLARDISTANCE" DOUBLE, "POLARBEARING" DOUBLE,
"ISADSB" BOOLEAN, "ISONGROUND" BOOLEAN,
"LASTSEENTIME" TIMESTAMP, "POSUPDATETIME" TIMESTAMP, "BDS40SEENTIME" TIMESTAMP)